ENCODER_MAP_ENABLE = yes
LTO_ENABLE = yes
VIA_ENABLE = yes
OLED_ENABLE = yes

CONSOLE_ENABLE = no
COMMAND_ENABLE = no	
MOUSEKEY_ENABLE = no

GRAVE_ESC_ENABLE = no 
MAGIC_ENABLE = no

MUSIC_ENABLE = no